---
- name: Install Vector (Debian)
  apt:
    deb: "https://packages.timber.io/vector/{{ version }}/vector_{{ version }}-1_{{ arch }}.deb"
    install_recommends: yes
  vars:
    version: "{{ (vector_version == 'nightly')| bool | ternary('nightly/latest', vector_version) }}"
    arch: "{{ vector_debian_arch[ansible_machine] }}"
  when: ansible_os_family == 'Debian'

- name: Install Vector (RedHat)
  yum:
    name: "https://packages.timber.io/vector/{{ version }}/vector-{{ package_version }}.{{ arch }}.rpm"
    state: present
    disable_gpg_check: yes # package is not signed
  vars:
    version: "{{ (vector_version == 'nightly')| bool | ternary('nightly/latest', vector_version) }}"
    package_version: "{{ vector_version is match('latest') | ternary(vector_version, vector_version ~ '-1') }}"
    arch: "{{ vector_redhat_arch[ansible_machine] }}"
  when: ansible_os_family == 'RedHat'

- name: Deploy config Vector
  ansible.builtin.template:
    src: vector.j2
    dest: "{{ vector_config_path }}"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
- name: Creates directory
  file:
    path: /var/lib/vector/local_logs
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
- name: Create systemd unit Vector
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
